### ISSUE TITLE
Since you have mentioned that you have used mediaeval 2016, images of testset like airstrikes_1 url is not mentioned .

### ISSUE THREAD

**Issue by vidhu22** [dhruvkhattar/MVAE#5]
Since you have mentioned that you have used mediaeval 2016, images of testset like airstrikes_1 url is not mentioned .
How you you split the images in dev and test set

_Originally posted by @vidhu22 in https://github.com/dhruvkhattar/MVAE/issues/3#issuecomment-580343803_

**Comment by dhruvkhattar** [comment]
We filter out all the posts which don't have attached images.
If you check out the dataset, it has different set of posts for dev and test.
